### ISSUE TITLE
Error while calling

### ISSUE THREAD

**Issue by mittal4792** [SiddAjmera/WebhookForMovieDB#1]
I used the steps you provided, as well as used the "Deploy" button for Heroku.
It gives the same error everywhere: "Cannot POST /"
Postman shows the same. With 404 Status.

**Comment by SiddAjmera** [comment]
@mittal4792 , not sure if you have issues with development or deployment, Can you please clarify? Also I'm not really active on GitHub maintaining this Repo. Please post further comments on the [Medium Article itself](https://chatbotslife.com/creating-a-nodejs-based-webhook-for-intelligent-bots-a91ecbe33402).
